[ClassVersion("1.0.0.0"), FriendlyName("OfficeOnlineServerHost")]
class MSFT_OfficeOnlineServerHost : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"),ValueMap{"Yes"},Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Ensure Present or Absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Host domains to which Office Online Server allows file operations requests")] String AllowList[];
};
