[ClassVersion("1.0.0.0"), FriendlyName("OfficeOnlineServerProductUpdate")]
class MSFT_OfficeOnlineServerProductUpdate : OMI_BaseResource
{
    [Key, Description("The name of the update setup file")] String SetupFile;
    [Required, Description("List of servers in the Office Online Server farm")] String Servers[];
    [Write, Description("Present to install Update. Absent is currently not supported"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

